#!/bin/bash

# 🚀 NEXTRADE AI DEPLOYMENT — 3 COMMANDS ONLY
# Déploiement complet Claude Multi-Horizon Trading

echo "════════════════════════════════════════════════════════"
echo "🚀 NEXTRADE AI — DEPLOYMENT MULTI-HORIZON TRADING"
echo "════════════════════════════════════════════════════════"
echo ""

# Commande 1: Vérifier que tout est prêt
echo "✅ ÉTAPE 1: Vérifier les changements prêts"
echo "---"
cd /tmp/nextrade-ai
git log --oneline -5
echo ""
echo "Status des fichiers:"
git status --short || echo "(Tout est committé)"
echo ""

# Commande 2: Pousser vers GitHub
echo "✅ ÉTAPE 2: Pousser vers GitHub"
echo "---"
echo "COMMANDE:"
echo "  git push origin main"
echo ""
echo "Exécution..."
# Ici, on va essayer le push
git push origin main 2>&1 || {
  echo ""
  echo "⚠️  Push échoué (authentification nécessaire)"
  echo "Solutions:"
  echo "  1. gh auth login (GitHub CLI)"
  echo "  2. git config --global credential.helper store"
  echo "  3. Ajouter token: git remote set-url origin https://<TOKEN>@github.com/Tamati987/nextrade-ai.git"
  echo ""
}

echo ""
echo "════════════════════════════════════════════════════════"
echo "✅ RÉSUMÉ DU DÉPLOIEMENT"
echo "════════════════════════════════════════════════════════"
echo ""
echo "📦 Fichiers NOUVEAUX:"
echo "   • claude-trading-decisioner.js"
echo "   • trading-engine-advanced.js"
echo "   • deploy.sh"
echo "   • DEPLOYMENT_CONFIG.md"
echo "   • DEPLOY_NOW.md"
echo ""
echo "✏️  Fichiers MODIFIÉS:"
echo "   • railway.json (script startup)"
echo ""
echo "📝 Commits PRÊTS (5 total):"
echo "   77eabdf 📖 Guide de déploiement final"
echo "   0010a82 ⚙️  Script de déploiement automatique Railway"
echo "   768345b 🚀 Claude Multi-Horizon Trading"
echo "   f2755fe 🎯 Claude Trading AI autonome"
echo "   469d96e 🧠 Claude Control avancé"
echo ""
echo "🧠 Fonctionnalités DÉPLOYÉES:"
echo "   ✅ Claude décide ACHATS court terme (0-4h)"
echo "   ✅ Claude décide ACHATS moyen terme (4h-1d)"
echo "   ✅ Claude décide ACHATS long terme (1-30j)"
echo "   ✅ Positions SIMULTANÉES sur 3 horizons"
echo "   ✅ Take Profit/Stop Loss intelligents par horizon"
echo "   ✅ Capital composé et alloué intelligemment"
echo ""
echo "⏱️  Timeline de déploiement après PUSH:"
echo "   T+0s:   GitHub reçoit le push"
echo "   T+5s:   Railway détecte les changements"
echo "   T+10s:  Build commence (npm install + deploy.sh)"
echo "   T+20s:  Server redémarre"
echo "   T+30s:  ✅ LIVE — Logs: '🚀 NexTrade AI ADVANCED'"
echo ""
echo "📊 Vérification après déploiement:"
echo "   • Railway Dashboard → nextrade-ai → Logs"
echo "   • Chercher: '🚀 NexTrade AI ADVANCED'"
echo "   • Chercher: '🧠 Claude Multi-Horizon'"
echo "   • Attendre 15 min pour le premier cycle de trading"
echo ""
echo "════════════════════════════════════════════════════════"
echo "🎉 PRÊT À DÉPLOYER!"
echo "════════════════════════════════════════════════════════"
